#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

[[ "$(id -u)" -eq 0 ]] && echo "Script must be run as a normal user." && exit

# Colors
RED="\033[1;31m"
GREEN="\033[1;32m"
END="\033[0m"

usage() {
  echo "
  Usage:
    -h, --help, help     | Print this message
    -u, --update, update | Update tlauncher.jar
    -r, --remove, remove | Remove tlauncher from your system, except your \$HOME/.minecraft dir
    nothing              | Launch TLauncher
  "
}

update() {
  echo -e "\n${GREEN}Downloading the latest version...${END}"
  wget https://tlauncher.org/jar -P /tmp
  unzip /tmp/jar -d /tmp/tlauncher
  sudo mv /tmp/tlauncher/*.jar /usr/share/tlauncher/tlauncher.jar
  rm /tmp/jar
  rm -rf /tmp/tlauncher/
  echo -e "\n${GREEN}Done!${END}"
}

remove() {
  SYSTEM_FILES=(
    /usr/share/tlauncher
    /usr/share/icons/tlauncher.png
    /usr/share/applications/tlauncher.desktop
    /usr/bin/tlauncher
  )
  echo -e "\n${GREEN}Removing TLauncher system files ...${END}"
  sudo rm -rf "${SYSTEM_FILES[@]}"
  echo -en "\nDo you want to keep the package \"jre-openjdk\" installed (${GREEN}Yy${END}/${RED}Nn${END})? " && read -r KEEP_JAVA
  echo -en "\nDo you want to keep your \"\$HOME/.tlauncher\" dir (${GREEN}Yy${END}/${RED}Nn${END})? " && read -r KEEP_DOTDIR
  [[ "${KEEP_JAVA,,}" = "n" ]] && sudo pacman -Rns jre-openjdk
  [[ "${KEEP_DOTDIR,,}" = "n" ]] && rm -rf "$HOME/.tlauncher"
  # This dir is created by tlauncher to save minecraft version
  if [[ -d "$HOME/.minecraft" ]]; then
    read -rp $'\nDo you want to keep your "$HOME/.minecraft" dir ('"${GREEN}Yy${END}/${RED}Nn${END}"')?: ' CLEAN_MINECRAFT
    [[ "${CLEAN_MINECRAFT,,}" == "n" ]] && rm -rf "$HOME/.minecraft"
  fi
  echo -e "\n${GREEN}TLauncher Removed!${END}"
}

case "${1:-}" in
-u | --update | update)
  update && exit
  ;;
-r | --remove | remove)
  remove && exit
  ;;
-h | --help | help)
  usage && exit
  ;;
*)
  exec java -jar /usr/share/tlauncher/tlauncher.jar
  ;;
esac
